name: ict3104
channels:
  - conda-forge
  - default
  - pytorch
dependencies:
  - python=3.8
  - pip=20.2.4
  - pip:
      - --find-links https://download.pytorch.org/whl/torch_stable.html
      - --requirement requirements.txt
